// Package mcpserver exposes core.Service as an MCP server over stdio, so
// the same three functions (research, draft_pitch, update_status) that
// power the REST API and web UI are also callable from any MCP client
// (Claude Desktop, a future Telegram bot's agent loop, etc).
package mcpserver

import (
	"context"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"outreach/internal/core"
)

func NewServer(svc *core.Service) *mcp.Server {
	server := mcp.NewServer(&mcp.Implementation{Name: "outreach", Version: "0.1.0"}, nil)

	mcp.AddTool(server, &mcp.Tool{
		Name: "research",
		Description: "Research a project: pulls what it does, team/socials, recent activity, and tone " +
			"into a structured brief via web search. Cached — pass refresh=true to force a re-run.",
	}, researchHandler(svc))

	mcp.AddTool(server, &mcp.Tool{
		Name: "draft_pitch",
		Description: "Draft an outreach message for a project given a goal (\"intro\", \"partnership pitch\", " +
			"\"follow-up\") and the cached research brief. Researches first if no brief exists yet.",
	}, draftHandler(svc))

	mcp.AddTool(server, &mcp.Tool{
		Name: "update_status",
		Description: "Move a project to a new pipeline stage (new, researched, reached_out, in_talks, " +
			"partnered, dead) and log a note about why.",
	}, updateStatusHandler(svc))

	mcp.AddTool(server, &mcp.Tool{
		Name:        "list_projects",
		Description: "List all tracked projects with their current stage.",
	}, listProjectsHandler(svc))

	return server
}

type researchArgs struct {
	ProjectID int64 `json:"project_id" jsonschema:"the numeric ID of the project to research"`
	Refresh   bool  `json:"refresh,omitempty" jsonschema:"force a fresh research pass even if a brief is cached"`
}

func researchHandler(svc *core.Service) mcp.ToolHandlerFor[researchArgs, any] {
	return func(ctx context.Context, req *mcp.CallToolRequest, args researchArgs) (*mcp.CallToolResult, any, error) {
		brief, err := svc.Research(ctx, args.ProjectID, args.Refresh)
		if err != nil {
			return errResult(err), nil, nil
		}
		return textResult(formatBrief(brief)), nil, nil
	}
}

type draftArgs struct {
	ProjectID int64  `json:"project_id" jsonschema:"the numeric ID of the project"`
	Goal      string `json:"goal" jsonschema:"what the message is for, e.g. intro, partnership pitch, follow-up"`
	Context   string `json:"context,omitempty" jsonschema:"optional extra context or voice guidance"`
}

func draftHandler(svc *core.Service) mcp.ToolHandlerFor[draftArgs, any] {
	return func(ctx context.Context, req *mcp.CallToolRequest, args draftArgs) (*mcp.CallToolResult, any, error) {
		if args.Goal == "" {
			return errResult(fmt.Errorf("goal is required")), nil, nil
		}
		draft, err := svc.DraftPitch(ctx, args.ProjectID, args.Goal, args.Context)
		if err != nil {
			return errResult(err), nil, nil
		}
		result := draft.Content
		if draft.Model != "" {
			result += fmt.Sprintf("\n\n(generated by %s)", draft.Model)
		}
		return textResult(result), nil, nil
	}
}

type updateStatusArgs struct {
	ProjectID int64  `json:"project_id" jsonschema:"the numeric ID of the project"`
	Stage     string `json:"stage" jsonschema:"new, researched, reached_out, in_talks, partnered, or dead"`
	Notes     string `json:"notes,omitempty" jsonschema:"optional note about this status change"`
}

func updateStatusHandler(svc *core.Service) mcp.ToolHandlerFor[updateStatusArgs, any] {
	return func(ctx context.Context, req *mcp.CallToolRequest, args updateStatusArgs) (*mcp.CallToolResult, any, error) {
		if err := svc.UpdateStatus(args.ProjectID, core.Stage(args.Stage), args.Notes); err != nil {
			return errResult(err), nil, nil
		}
		return textResult(fmt.Sprintf("project %d moved to %s", args.ProjectID, args.Stage)), nil, nil
	}
}

type listProjectsArgs struct{}

func listProjectsHandler(svc *core.Service) mcp.ToolHandlerFor[listProjectsArgs, any] {
	return func(ctx context.Context, req *mcp.CallToolRequest, args listProjectsArgs) (*mcp.CallToolResult, any, error) {
		projects, err := svc.ListProjects()
		if err != nil {
			return errResult(err), nil, nil
		}
		if len(projects) == 0 {
			return textResult("no projects tracked yet"), nil, nil
		}
		var b strings.Builder
		for _, p := range projects {
			fmt.Fprintf(&b, "#%d %s — %s\n", p.ID, p.Name, p.Stage)
		}
		return textResult(b.String()), nil, nil
	}
}

func formatBrief(b core.Brief) string {
	var out strings.Builder
	fmt.Fprintf(&out, "Summary: %s\n", b.Summary)
	if len(b.Team) > 0 {
		fmt.Fprintf(&out, "Team: %s\n", strings.Join(b.Team, ", "))
	}
	if len(b.Socials) > 0 {
		fmt.Fprintf(&out, "Socials: %s\n", strings.Join(b.Socials, ", "))
	}
	if len(b.RecentNews) > 0 {
		fmt.Fprintf(&out, "Recent activity: %s\n", strings.Join(b.RecentNews, "; "))
	}
	if b.Tone != "" {
		fmt.Fprintf(&out, "Tone: %s\n", b.Tone)
	}
	if b.Model != "" {
		fmt.Fprintf(&out, "(generated by %s)\n", b.Model)
	}
	return out.String()
}

func textResult(s string) *mcp.CallToolResult {
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: s}}}
}

func errResult(err error) *mcp.CallToolResult {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{&mcp.TextContent{Text: err.Error()}},
	}
}
